(function () {
  "use strict";
  const brand=window.__BRAND__||{},engine=brand.fractionEngine,storageKey=brand.storageKey||"chispora.mvp.v1",$=(s,c)=>(c||document).querySelector(s),$$=(s,c)=>Array.from((c||document).querySelectorAll(s));
  let difficulty="explorador",game=null,elapsed=0,started=0,clock=0,paused=false,recorded=false;
  function read(){try{const value=JSON.parse(localStorage.getItem(storageKey)||"{}");return value&&typeof value==="object"?value:{}}catch(_){return{}}}
  function save(state){try{localStorage.setItem(storageKey,JSON.stringify(state));return true}catch(error){console.warn("[fraction-storage] No se pudo guardar:",error);return false}}
  function time(){return Math.max(0,Math.floor((elapsed+(started?Date.now()-started:0))/1000))} function format(value){return Math.floor(value/60)+":"+String(value%60).padStart(2,"0")}
  function tick(){const el=$("[data-fraction-time]");if(el)el.textContent=format(time())} function startClock(){if(started||!game||paused||game.status==="complete")return;started=Date.now();clock=setInterval(tick,250);tick()} function stopClock(){if(started){elapsed+=Date.now()-started;started=0}clearInterval(clock);clock=0;tick()}
  function model(pair,small){const n=pair[0],d=pair[1];return '<div class="fraction-model'+(small?' fraction-model-small':'')+'" style="--parts:'+d+'" aria-label="'+n+' de '+d+' partes">'+Array.from({length:d},(_,i)=>'<span class="'+(i<n?'is-filled':'')+'"></span>').join("")+'</div><strong class="fraction-label">'+n+'/'+d+'</strong>'}
  function render(){if(!game)return;const round=game.rounds[game.currentRound],feedback=game.status==="feedback";$("[data-fraction-round]").textContent=game.currentRound+1;$("[data-fraction-total]").textContent=game.roundCount;$("[data-fraction-score]").textContent=game.correctAnswers;$("[data-fraction-prompt]").textContent=round.prompt;const visual=$("[data-fraction-visual]");visual.innerHTML=model(round.left,false)+(round.right?'<span class="fraction-relation">?</span>'+model(round.right,false):"");$("[data-fraction-options]").innerHTML=round.options.map((option)=>{const rejected=game.rejectedOptions.includes(option),correct=feedback&&game.lastCorrect&&option===round.answer,disabled=paused||game.status!=="playing"||rejected,pair=/^(\d+)\/(\d+)$/.exec(option);return '<button class="fraction-option'+(rejected?' is-rejected':'')+(correct?' is-correct':'')+'" type="button" data-fraction-answer="'+option+'"'+(disabled?' disabled':'')+'>'+(round.type==="equivalent"&&pair?model([Number(pair[1]),Number(pair[2])],true):'<strong>'+option+'</strong>')+'</button>'}).join("");const explanation=$("[data-fraction-explanation]");explanation.hidden=!(feedback&&game.lastCorrect);explanation.textContent=feedback&&game.lastCorrect?round.explanation:"";const next=$("[data-fraction-continue]");next.hidden=!feedback;next.textContent=game.lastCorrect?(game.currentRound===game.roundCount-1?"Ver resultado":"Siguiente desafío"):"Intentar otra vez";$("[data-fraction-card]").classList.toggle("is-paused",paused);tick()}
  function message(text){$("[data-fraction-message]").textContent=text} function start(level,navigate){stopClock();difficulty=engine.difficulties[level]?level:"explorador";game=engine.createGame(difficulty);elapsed=0;started=0;paused=false;recorded=false;render();message("Observa las partes antes de responder.");startClock();if(navigate!==false)location.hash="partida-fracciones"}
  function ensure(state){state.progress=state.progress&&typeof state.progress==="object"?state.progress:{completedGames:0};state.progress.fraction=state.progress.fraction||{completedByDifficulty:{},bestExtraAttempts:{},totalChallenges:0};const p=state.progress.fraction;p.completedByDifficulty=p.completedByDifficulty||{};p.bestExtraAttempts=p.bestExtraAttempts||{};p.totalChallenges=Number(p.totalChallenges||0);return p}
  function progress(){const state=read(),p=ensure(state),count=Object.keys(p.completedByDifficulty).filter((key)=>p.completedByDifficulty[key]).length,bar=$("[data-fraction-progress]");if(bar){bar.setAttribute("aria-valuenow",Math.round(count/3*100));$("span",bar).style.width=Math.round(count/3*100)+"%"}$("[data-fraction-progress-label]").textContent=count?count+" de 3 niveles completados":"Listo para jugar";$("[data-fraction-levels]").textContent=count+"/3"}
  function finish(){if(!game||recorded)return;stopClock();recorded=true;const seconds=time(),state=read(),p=ensure(state),id=game.difficulty;p.completedByDifficulty[id]=true;p.totalChallenges+=game.correctAnswers;if(typeof p.bestExtraAttempts[id]!=="number"||game.extraAttempts<p.bestExtraAttempts[id])p.bestExtraAttempts[id]=game.extraAttempts;state.progress.completedGames=Number(state.progress.completedGames||0)+1;save(state);window.dispatchEvent(new CustomEvent("chispora:state-updated",{detail:state}));progress();$$('[data-completed-games]').forEach((el)=>el.textContent=state.progress.completedGames);$("[data-fraction-result-rounds]").textContent=game.roundCount+" desafíos";$("[data-fraction-result-attempts]").textContent=game.extraAttempts+(game.extraAttempts===1?" intento extra":" intentos extra");$("[data-fraction-result-level]").textContent=engine.difficulties[id].name;$("[data-fraction-result-time]").textContent=format(seconds);location.hash="resultado-fracciones"}
  function next(){const was=game.lastCorrect,result=engine.continueGame(game);if(result.complete){finish();return}render();message(was?"Nuevo desafío. Compara las partes.":"Mira nuevamente el modelo y prueba otra opción.")}
  function init(){if(!engine)return;const select=$("[data-fraction-difficulty]"),summary=$("[data-fraction-difficulty-summary]");const saved=read(),preferred=saved.settings&&saved.settings.preferredDifficulty;if(preferred&&preferred!=="auto"&&engine.difficulties[preferred])select.value=difficulty=preferred;function update(){const config=engine.difficulties[select.value];difficulty=config.id;const labels=[config.roundCount+" desafíos",config.description,"Modelos visuales de partes iguales"];$$('strong, span',summary).forEach((el,i)=>el.textContent=labels[i])}select.addEventListener("change",update);update();$("[data-fraction-options]").addEventListener("click",(event)=>{const button=event.target.closest("[data-fraction-answer]");if(!button||!game||paused)return;const result=engine.submitAnswer(game,button.dataset.fractionAnswer);if(!result.accepted)return;render();message(result.correct?"¡Correcto! Revisa la explicación.":"Esa opción no representa el modelo. Puedes intentarlo otra vez.")});$("[data-fraction-continue]").addEventListener("click",next);document.addEventListener("click",(event)=>{if(event.target.closest("[data-start-fraction]"))start(select.value,true);if(event.target.closest("[data-restart-fraction], [data-replay-fraction]"))start(difficulty,true)});const pause=$("[data-fraction-pause-dialog]"),exit=$("[data-fraction-exit-dialog]");document.addEventListener("click",(event)=>{if(event.target.closest("[data-fraction-pause]")){paused=true;stopClock();render();pause.showModal()}if(event.target.closest("[data-fraction-exit]")){paused=true;stopClock();render();exit.showModal()}});function resume(){if(!game||!paused)return;paused=false;startClock();render()}pause.addEventListener("close",resume);exit.addEventListener("close",()=>{if(exit.returnValue!=="exit")resume()});$("[data-fraction-confirm-exit]").addEventListener("click",()=>{exit.close("exit");stopClock();game=null;paused=false;location.hash="misiones"});progress();addEventListener("hashchange",()=>{if(location.hash==="#partida-fracciones"&&(!game||game.status==="complete"))start(difficulty,false);else if(location.hash!=="#partida-fracciones"&&game&&game.status!=="complete"){stopClock();game=null;paused=false}});if(location.hash==="#partida-fracciones")start(difficulty,false)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
