"use strict";
const assert = require("node:assert/strict"); const fs = require("node:fs"); const path = require("node:path"); const vm = require("node:vm");
const source = fs.readFileSync(path.join(__dirname, "..", "lib", "fraction-engine.js"), "utf8"); const context = { window: { __BRAND__: {} }, Math: Math }; vm.createContext(context); vm.runInContext(source, context); const engine = context.window.__BRAND__.fractionEngine;
function test(name, run) { try { run(); process.stdout.write("✓ " + name + "\n"); } catch (error) { process.stderr.write("✗ " + name + "\n"); throw error; } }
test("crea tres niveles sin rondas repetidas", () => { [["explorador",5],["aventurero",6],["maestro",7]].forEach(([id,count]) => { const game=engine.createGame(id,()=>0.4); assert.equal(game.rounds.length,count); assert.equal(new Set(game.rounds.map((round)=>round.id)).size,count); game.rounds.forEach((round)=>assert.ok(round.options.includes(round.answer))); }); });
test("recupera Explorador ante una dificultad inválida", () => { assert.equal(engine.createGame("otra",()=>0.2).difficulty,"explorador"); });
test("rechaza respuestas inválidas, repetidas y bloqueadas", () => { const game=engine.createGame("explorador",()=>0.3); const round=game.rounds[0]; assert.equal(engine.submitAnswer(game,"x").reason,"invalid"); const wrong=round.options.find((item)=>item!==round.answer); engine.submitAnswer(game,wrong); assert.equal(engine.submitAnswer(game,wrong).reason,"locked"); engine.continueGame(game); assert.equal(engine.submitAnswer(game,wrong).reason,"rejected"); });
test("un error no avanza y un acierto sí", () => { const game=engine.createGame("aventurero",()=>0.5); const round=game.rounds[0]; engine.submitAnswer(game,round.options.find((item)=>item!==round.answer)); engine.continueGame(game); assert.equal(game.currentRound,0); assert.equal(game.extraAttempts,1); engine.submitAnswer(game,round.answer); engine.continueGame(game); assert.equal(game.currentRound,1); assert.equal(game.correctAnswers,1); assert.equal(game.rejectedOptions.length,0); });
test("completa exactamente después de la última ronda", () => { const game=engine.createGame("maestro",()=>0.6); for(let i=0;i<game.roundCount;i+=1){ engine.submitAnswer(game,game.rounds[game.currentRound].answer); assert.equal(engine.continueGame(game).complete,i===game.roundCount-1); } assert.equal(game.status,"complete"); });
process.stdout.write("\nTodas las pruebas del motor de Fracciones en acción pasaron.\n");
