"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm"); const source=fs.readFileSync(path.join(__dirname,"..","lib","robot-engine.js"),"utf8"),context={window:{__BRAND__:{}},Math}; vm.createContext(context);vm.runInContext(source,context);const engine=context.window.__BRAND__.robotEngine;
function test(name,run){try{run();process.stdout.write("✓ "+name+"\n");}catch(error){process.stderr.write("✗ "+name+"\n");throw error;}}
function load(game,commands){commands.forEach((command)=>assert.equal(engine.addCommand(game,command).accepted,true));}
test("crea niveles con tableros válidos y soluciones comprobables",()=>{[["explorador",4,4],["aventurero",5,5],["maestro",6,6]].forEach(([id,count,size])=>{const game=engine.createGame(id,()=>0.4);assert.equal(game.rounds.length,count);assert.equal(new Set(game.rounds.map((round)=>round.id)).size,count);game.rounds.forEach((round)=>{assert.equal(round.size,size);assert.ok(!round.obstacles.includes(round.start));assert.ok(!round.obstacles.includes(round.goal));const probe={difficulty:id,roundCount:1,rounds:[round],currentRound:0,program:[],correctAnswers:0,extraAttempts:0,hintsUsed:0,hintedRounds:[],lastCorrect:false,lastResult:null,status:"playing"};load(probe,round.solution);assert.equal(engine.runProgram(probe).correct,true);});});});
test("rechaza comandos inválidos, vacíos y sobre el límite",()=>{const game=engine.createGame("explorador",()=>0.2);assert.equal(engine.addCommand(game,"jump").reason,"invalid");assert.equal(engine.runProgram(game).reason,"empty");for(let i=0;i<game.rounds[0].maxCommands;i+=1)engine.addCommand(game,"right");assert.equal(engine.addCommand(game,"right").reason,"limit");});
test("permite quitar, limpiar y usar una pista una vez",()=>{const game=engine.createGame("aventurero",()=>0.3);engine.addCommand(game,"up");assert.equal(engine.removeCommand(game),true);engine.addCommand(game,"down");assert.equal(engine.clearProgram(game),true);assert.ok(engine.useHint(game));engine.useHint(game);assert.equal(game.hintsUsed,1);});
test("un choque permite corregir sin avanzar",()=>{const game=engine.createGame("aventurero",()=>0.5);load(game,["right","right","right","right","right"]);const result=engine.runProgram(game);assert.equal(result.correct,false);assert.ok(["edge","obstacle","short"].includes(result.reason));engine.continueGame(game);assert.equal(game.currentRound,0);assert.equal(game.extraAttempts,1);assert.ok(game.program.length>0);});
test("una solución avanza y completa exactamente al final",()=>{const game=engine.createGame("explorador",()=>0.6);for(let i=0;i<game.roundCount;i+=1){load(game,game.rounds[game.currentRound].solution);assert.equal(engine.runProgram(game).correct,true);assert.equal(engine.continueGame(game).complete,i===game.roundCount-1);}assert.equal(game.status,"complete");assert.equal(game.correctAnswers,game.roundCount);});
process.stdout.write("\nTodas las pruebas del motor de Programa al robot pasaron.\n");
